### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by FlashDog123** [dobots/crownstone-app#2]
als ik stap 4.3 van jullie handleiding probeer uit te voeren krijg deze errors(zie foto).
Justin
![screenshot from 2015-03-06 13 07 22](https://cloud.githubusercontent.com/assets/6916895/6525137/171df5ba-c402-11e4-97e7-25c151b9f61a.png)

**Comment by mrquincle** [comment]
@FlashDog123 Thanks for your report. It's nice to see the output, makes it easy for us. Please, ask next time in English, because then more of my colleagues can help.

The problem is with the version of cordova. So if you installed it a long time ago, even a few weeks ago, it might be outdated. You can check with:

    cordova -v

This should be version `4.3.0`.

If this is not the case, install the newest version:

    sudo npm install -g cordova

And then try to apply the fix:

    ./fix-name.sh

Then you shouldn't have any errors.

**Comment by mrquincle** [comment]
If you actually do have the version `4.3.0`, then you have probably run things as `sudo` which you should **NOT** do!!

You will find other people that have a problem with:

    cd ~/crownstone-app/scripts
    cordova platform add android

Namely on for example http://stackoverflow.com/questions/27211279/unable-to-fetch-platform-android-error-eacces. In your case it seems that `/home/ubuntu/tmp` is not owned by you. `ls` will probably show that it is owned by `root`. To correct it:

    sudo chown -R ubuntu.ubuntu /home/ubuntu/tmp

Or remove it. Just don't make a habit of using `sudo`...

**Comment by FlashDog123** [comment]
@mrquincle that did it! It might be handy tot add thuis to your google docs manual, since I followed your manual to the letter. Andere i recone other people will face the same problems

And i also have one onther question: is there a way to save the files to my harddrive? Since i don't really like to redownload everthing again the next time i boot my laptop up.

**Comment by mrquincle** [comment]
@FlashDog123 Please, ask separate questions in separate issues. Apart from that, if you use the USB disk, adaptation and alterations will be saved on the stick. If you use another method like a virtual machine on a Mac, you will have to figure it out yourself to get it persistent.
